### PR TITLE
destroy ambiente

### PR DESCRIPTION
**Pull request by ericrr**

### CODE REVIEW

**Comment by ericrr** [comment]
atlandis plan -- -destroy

**Review by ericrr-aprov — APPROVED** [review]

**Comment by ericrr** [comment]
atlantis plan -- -destroy

**Comment by ericrr** [comment]
Ran Plan for 0 projects:

**Comment by ericrr** [comment]
atlandis -- -destroy

**Comment by ericrr** [comment]
atlandis -- destroy

**Comment by ericrr** [comment]
atlantis plan -- -destroy

**Comment by ericrr** [comment]
Ran Plan for 0 projects:

**Comment by ericrr** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/usr/local/bin/terraform plan -input=false -refresh -no-color -out \"/atlantis/repos/ericrr/atlantis/23/default/default.tfplan\"" in "/atlantis/repos/ericrr/atlantis/23/default": exit status 1
Eu sou um script customizado


Error: No configuration files

Plan requires configuration to be present. Planning without a configuration
would mark everything for destruction, which is normally not what is desired.
If you would like to destroy everything, run plan with the -destroy option.
Otherwise, create a Terraform configuration file (.tf file) and try again.


```

**Comment by ericrr** [comment]
atlantis apply

**Comment by ericrr** [comment]
Ran Apply for 0 projects:

**Comment by ericrr** [comment]
atlantis plan -- -destroy

**Comment by ericrr** [comment]
Ran Plan for dir: `.` workspace: `default`

```diff
Eu sou um script customizado


No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Eu sou um script customizado

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis.alfacode.site/lock?id=ericrr%252Fatlantis%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d . -- -destroy`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by ericrr** [comment]
**Warning**: The plan for dir: `.` workspace: `default` was **discarded** via the Atlantis UI.

To `apply` this plan you must run `plan` again.

**Comment by ericrr** [comment]
atlantis plan -d . -- -destroy

**Comment by ericrr** [comment]
Ran Plan for dir: `.` workspace: `default`

```diff
Eu sou um script customizado


No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Eu sou um script customizado

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis.alfacode.site/lock?id=ericrr%252Fatlantis%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d . -- -destroy`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Comment by ericrr** [comment]
atlantis apply

**Comment by ericrr** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

```

**Comment by ericrr** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by ericrr** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Comment by ericrr** [comment]
atlantis plan -d . -- -destroy

**Comment by ericrr** [comment]
Atlantis commands can't be run on closed pull requests

**Pull request merged**
