### PR TITLE
porta 80

### PR DESCRIPTION
**Pull request by ericrr**

### CODE REVIEW

**Comment by ericrr** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
Eu sou um script customizado


An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
~ update in-place

Terraform will perform the following actions:

  # aws_security_group.sg-jumpbox-dev will be updated in-place
~ resource "aws_security_group" "sg-jumpbox-dev" {
        arn                    = "arn:aws:ec2:us-east-2:036079242480:security-group/sg-0c6c6e1e3a6aef991"
        description            = "sg-pes-dev-std-dev"
        egress                 = [
            {
                cidr_blocks      = [
                    "0.0.0.0/0",
                ]
                description      = ""
                from_port        = 0
                ipv6_cidr_blocks = []
                prefix_list_ids  = []
                protocol         = "-1"
                security_groups  = []
                self             = false
                to_port          = 0
            },
        ]
        id                     = "sg-0c6c6e1e3a6aef991"
      ~ ingress                = [
            {
                cidr_blocks      = [
                    "0.0.0.0/0",
                ]
                description      = "Acesso SSH "
                from_port        = 22
                ipv6_cidr_blocks = []
                prefix_list_ids  = []
                protocol         = "tcp"
                security_groups  = []
                self             = false
                to_port          = 22
            },
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = "Acesso SSH "
              + from_port        = 80
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = []
              + self             = false
              + to_port          = 80
            },
        ]
        name                   = "pes-dev-std-dev"
        owner_id               = "036079242480"
        revoke_rules_on_delete = false
        tags                   = {
            "Deploy" = "terraform"
            "Name"   = "pes-dev-std-dev"
        }
        vpc_id                 = "vpc-e545f58e"
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Warning: Interpolation-only expressions are deprecated

  on main.tf line 21, in resource "aws_instance" "jumpbox":
  21:     subnet_id = "${element(tolist(data.aws_subnet_ids.private.ids), count.index)}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.


Eu sou um script customizado

```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](http://atlantis.alfacode.site/lock?id=ericrr%252Fatlantis%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`

**Review by ericrr-aprov — APPROVED** [review]

**Comment by ericrr** [comment]
atlantis apply

**Comment by ericrr** [comment]
Ran Apply for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
aws_security_group.sg-jumpbox-dev: Modifying... [id=sg-0c6c6e1e3a6aef991]
aws_security_group.sg-jumpbox-dev: Modifications complete after 1s [id=sg-0c6c6e1e3a6aef991]

Warning: Interpolation-only expressions are deprecated

  on main.tf line 21, in resource "aws_instance" "jumpbox":
  21:     subnet_id = "${element(tolist(data.aws_subnet_ids.private.ids), count.index)}"

Terraform 0.11 and earlier required all non-constant expressions to be
provided via interpolation syntax, but this pattern is now deprecated. To
silence this warning, remove the "${ sequence from the start and the }"
sequence from the end of this expression, leaving just the inner expression.

Template interpolation syntax is still used to construct strings from
expressions when the template includes multiple interpolation sequences or a
mixture of literal strings and interpolations. This deprecation applies only
to templates that consist entirely of a single interpolation sequence.


Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

```
</details>

**Comment by ericrr** [comment]
Automatically merging because all plans have been successfully applied.

**Comment by ericrr** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
